const express = require('express')
const app = express()
const cookieParser = require('cookie-parser')
const http = require('http')
const {login, logout, changePass} = require('./login/login')
const {createHeadManager, createTeam, createTeamLeader, createTeamMember, addAdmin, removeAdmin, removeTeam, removeTeamLeader, removeTeamMember, getHeadManager, showFromDB} = require('./admin/handlers')
const {getAssignedTasks, assignTask, assignToNewTeam, extendDeadline, updateTask, removeTask} = require('./head_manager/handlers')
const {showAssignedTasks, assignToMembers, updateAssignedTo, trackProgress, viewCommentsForTask} = require('./team_leader/handlers')
const {viewAssignedTasks, updateProgress, addComent, removeComment} = require('./team_member/handlers')
const PORT = 8000
const server = http.createServer(app)
//express middleware
app.use(express.json())
app.use(cookieParser())

//API endpoints
app.post('/api/login', login)
app.post('/api/logout', logout)
app.patch('/api/changePassword', changePass)
app.post('/api/admin/show', showFromDB)
app.post('/api/admin/show/manager', getHeadManager)
app.post('/api/admin/create/manager', createHeadManager)
app.post('/api/admin/create/team', createTeam)
app.post('/api/admin/create/leader', createTeamLeader)
app.post('/api/admin/create/member', createTeamMember)
app.post('/api/admin/create/admin', addAdmin)
app.delete('/api/admin/remove/admin', removeAdmin)
app.delete('/api/admin/remove/team', removeTeam)
app.delete('/api/admin/remove/leader', removeTeamLeader)
app.delete('/api/admin/remove/member', removeTeamMember)
app.delete('/api/admin/remove/admin', removeAdmin)
app.post('/api/manager/task/assign', assignTask)
app.post('/api/manager/task/assigned', getAssignedTasks)
app.patch('/api/manager/task/change', assignToNewTeam)
app.patch('/api/manager/task/update', updateTask)
app.patch('/api/manager/task/deadline/extend', extendDeadline)
app.delete('/api/manager/task/remove', removeTask)
app.get('/api/leader/tasks/assigned', showAssignedTasks)
app.post('/api/leader/tasks/assign', assignToMembers)
app.patch('/api/leader/tasks/update', updateAssignedTo)
app.post('/api/leader/tasks/progress', trackProgress)
app.post('/api/leader/comments', viewCommentsForTask)
app.get('/api/member/tasks', viewAssignedTasks)
app.patch('/api/member/tasks/progress', updateProgress)
app.post('/api/member/comments/add', addComent)
app.delete('/api/member/comments/remove', removeComment)

app.listen(PORT , ()=> console.log(`app is running on port ${PORT}`))